import client

key = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjkwMDJiMWE3LTRhMTItNDdhMy04MDU2LTU5YmFiZTZmZmVjZiIsImlhdCI6MTYwOTE5Njc3Mywic3ViIjoiZGV2ZWxvcGVyL2MyMGJhNThjLTlkNGUtMDFkZC01YzUwLTI5ZDMzZDZlMDNjNiIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyIxMjguMTI4LjEyOC4xMjgiXSwidHlwZSI6ImNsaWVudCJ9XX0.1RKFtdown15NHs9gv32_25jsS2iS7uhrrM0Q2RjRTWNwVAYVwe9Q3FvscLn20DZU9ZhvJ_1vziLATz98JrzShg'
proxy_url = 'https://proxy.royaleapi.dev/v1'
url = 'https://www.github.com/royaleapi/cr-api-data'

c = client.Client(token=key, url=proxy_url)
players = c.get_top_players(limit=1)

print(players)